services:
  timescaledb:
    image: timescale/timescaledb:2.17.2-pg16
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: my_timescale_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    networks:
      - backend
    restart: unless-stopped

  collector:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: collector
    environment:
      DB_HOST: timescaledb
      DB_NAME: my_timescale_db
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      API_KEY: your_api_key
      API_SECRET: your_api_secret
    ports:
      - "5000:5000"
    depends_on:
      - timescaledb
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  timescale_data:
    driver: local
